### ISSUE TITLE
TypeError: single_obj_bb_yolo_conversion() missing 1 required positional argument: 'class_names'

### ISSUE THREAD

**Issue by enemy7523** [muhammad-faizan-122/yolo-data-augmentation#1]
How can i solve this erro>?

**Comment by MMichalska-Scanway** [comment]
For anyone who has this problem - solution is pretty easy, there's a typo in line 26 of apply_album_aug.py
You have to change:
`transformed_bboxes = [single_obj_bb_yolo_conversion(transformed_bboxes[0]), classes]`
to
`transformed_bboxes = [single_obj_bb_yolo_conversion(transformed_bboxes[0], classes)]`

**Comment by MMichalska-Scanway** [comment]
@muhammad-faizan-122 please fix it or allow pushing to secondary branches so I'll fix it for you and make a pull request :)
