### ISSUE TITLE
Yolov5 + Data Albumentations integrated

### ISSUE THREAD

**Issue by yeongnamtan** [muhammad-faizan-122/yolo-data-augmentation#2]
when I run train.py,  I get below.... is albumentations turned on ??  what does 'always_apply' mean ? Do I need to specify albumentations when I run training

albumentations: Blur(always_apply=False, p=0.01, blur_limit=(3, 7)), MedianBlur(always_apply=False, p=0.01, blur_limit=(3, 7)), ToGray(always_apply=False, p=0.01), CLAHE(always_apply=False, p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8)), RandomBrightnessContrast(always_apply=False, p=0.01, brightness_limit=(-0.2, 0.2), contrast_limit=(-0.2, 0.2), brightness_by_max=True)

**Comment by gauritomar** [comment]
@yeongnamtan Are you referring to the train.py belonging to the ultralytics/yolov5? If so, you can add online data augementation by adding a hyperparameters yaml file 
Refer here: https://github.com/ultralytics/yolov5/discussions/7319

**Comment by muhammad-faizan-122** [comment]
Hi @yeongnamtan, 
This repository is not inked with [ultralytics](https://github.com/ultralytics/ultralytics)
